package org.bloomreach.inspections.core.reports

import org.bloomreach.inspections.core.engine.InspectionResults
import org.bloomreach.inspections.core.engine.Severity
import java.nio.file.Files
import java.nio.file.Path
import java.time.LocalDateTime
import java.time.format.DateTimeFormatter

/**
 * Generates Markdown format inspection reports.
 */
class MarkdownReportGenerator : ReportGenerator {

    override fun generate(results: InspectionResults, outputPath: Path) {
        val markdown = buildReport(results)
        Files.createDirectories(outputPath.parent)
        Files.writeString(outputPath, markdown)
    }

    private fun buildReport(results: InspectionResults): String {
        return buildString {
            // Header
            appendLine("# Bloomreach CMS Inspection Report")
            appendLine()
            appendLine("**Generated:** ${LocalDateTime.now().format(DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss"))}")
            appendLine()
            appendLine("---")
            appendLine()

            // Summary
            appendLine("## Summary")
            appendLine()
            appendLine("| Metric | Count |")
            appendLine("|--------|-------|")
            appendLine("| Total Issues | ${results.totalIssues} |")
            appendLine("| Errors | ${results.errorCount} |")
            appendLine("| Warnings | ${results.warningCount} |")
            appendLine("| Info | ${results.infoCount} |")
            appendLine("| Hints | ${results.hintCount} |")
            appendLine()

            // By Category
            if (results.issuesByCategory.isNotEmpty()) {
                appendLine("## Issues by Category")
                appendLine()
                appendLine("| Category | Count |")
                appendLine("|----------|-------|")
                results.issuesByCategory.forEach { (category, issues) ->
                    appendLine("| ${category.displayName} | ${issues.size} |")
                }
                appendLine()
            }

            // Detailed Issues
            if (results.issues.isNotEmpty()) {
                appendLine("## Detailed Issues")
                appendLine()

                // Group by file
                val issuesByFile = results.issues.groupBy { it.file }

                issuesByFile.forEach { (file, fileIssues) ->
                    appendLine("### ${file.name}")
                    appendLine()
                    appendLine("**Path:** `${file.path}`")
                    appendLine()

                    fileIssues.forEach { issue ->
                        val icon = when (issue.severity) {
                            Severity.ERROR -> "[ERROR]"
                            Severity.WARNING -> "[WARNING]"
                            Severity.INFO -> "[INFO]"
                            Severity.HINT -> "[HINT]"
                        }

                        appendLine("#### $icon ${issue.inspection.name}")
                        appendLine()
                        appendLine("- **Severity:** ${issue.severity.name}")
                        appendLine("- **Location:** Line ${issue.range.startLine}, Column ${issue.range.startColumn}")
                        appendLine("- **Inspection ID:** `${issue.inspection.id}`")
                        appendLine("- **Category:** ${issue.inspection.category.displayName}")
                        appendLine()
                        appendLine("**Message:**")
                        appendLine()
                        appendLine("> ${issue.message}")
                        appendLine()

                        if (issue.description.isNotBlank()) {
                            appendLine()
                            appendLine(issue.description)
                            appendLine()
                        }
                    }
                }
            }

            // Footer
            appendLine("---")
            appendLine()
            appendLine("*Report generated by Bloomreach CMS Inspections Tool v1.0.0*")
        }
    }
}
